<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\images\Users\167929a9-361a-416a-a599-07715a9de395\**" />
    <Content Remove="wwwroot\images\Users\167929a9-361a-416a-a599-07715a9de395\**" />
    <EmbeddedResource Remove="wwwroot\images\Users\167929a9-361a-416a-a599-07715a9de395\**" />
    <None Remove="wwwroot\images\Users\167929a9-361a-416a-a599-07715a9de395\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="MailKit" Version="4.12.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.16" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.16" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.16">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Drawing.Common" Version="8.0.13" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\images\Users\893a153a-7cea-4329-a276-b2030893fd74\ImagePrompt\" />
    <Folder Include="wwwroot\images\Users\893a153a-7cea-4329-a276-b2030893fd74\ImageToImage\" />
  </ItemGroup>

</Project>
